# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_customuser_data_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2017, 7, 15, 0, 51, 59, 963491, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
