# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 00:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2017, 7, 15, 0, 53, 13, 540067, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
