# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_auto_20170714_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='congressoPais',
            field=models.BooleanField(default=False),
        ),
    ]
