# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_auto_20170714_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usuario',
        ),
    ]
