# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 03:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_remove_customuser_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_endereco',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nº'),
        ),
    ]
