# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 02:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criancas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=254, verbose_name='Sobrenome')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('vai_participar', models.BooleanField(default=False, verbose_name='Irá ao evento?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=254, verbose_name='Sobrenome')),
                ('profissao', models.CharField(max_length=254, verbose_name='Profissão')),
                ('telefone', models.CharField(help_text='Ex.: 7133990000 -> 10 digitos', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefone')),
                ('celular', models.CharField(help_text='Ex.: 71998123456 -> 11 ou 10 (sem o 9 adicional) digitos', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Celular')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('vai_participar', models.BooleanField(default=False, verbose_name='Irá ao evento?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conhecimento', models.CharField(choices=[('igreja', 'Qual igreja?'), ('perfil', 'Em qual perfil?'), ('pagina', 'Em qual página?')], max_length=6, verbose_name='Como conheceu o congresso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
