# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 04:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('congressoPais_app', '0002_auto_20170715_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_nasc',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(help_text='Ex.: 71998123456 -> 11 ou 10 (sem o 9 adicional) digitos', max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('/\\(?([0-9]{2})\\)?([ ]?)([0-9]{4})\x02([0-9]{4})/', 'Ta errado cara..')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='data_nasc',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(help_text='Ex.: 7133990000 -> 10 digitos', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('/\\(?([0-9]{2})\\)?([ ]?)([0-9]{4})\x02([0-9]{4})/', 'Ta errado cara..')], verbose_name='Telefone'),
        ),
    ]
