# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congressoPais_app', '0003_auto_20170716_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(help_text='Ex.: 71998123456 -> 11 ou 10 (sem o 9 adicional) digitos', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(help_text='Ex.: 7133990000 -> 10 digitos', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefone'),
        ),
    ]
